#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  May 14, 2025 09:15:08 PM BST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top4 {base} {
    global vTcl
    if {$base == ""} {
        set base .top4
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m48 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 747x727+871+395
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 5124 1678
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Auto Marker"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m48" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    button "$top.but57" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Exit" 
    vTcl:DefineAlias "$top.but57" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but57 <Button-1> {
        lambda e: btnExit_lclick(e)
    }
    button "$top.but58" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "btn_Help" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Help" 
    vTcl:DefineAlias "$top.but58" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "BEFORE YOU START:" 
    vTcl:DefineAlias "$top.lab49" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "- Create an empty folder that is going to contain the cleaned submissions." 
    vTcl:DefineAlias "$top.lab58" "Label9" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$top.lab48" \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -text "Non-Cleaned Submissions" -background #d9d9d9 -height 187 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 709 
    vTcl:DefineAlias "$top.lab48" "frameTop" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab48
    button "$site_3_0.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "btn_GetTestFiles" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Select Folder" 
    vTcl:DefineAlias "$site_3_0.but52" "btnTestFiles" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "btn_GetNonClean" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Select Folder" 
    vTcl:DefineAlias "$site_3_0.but50" "btnGetnonClean" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab62" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Choose the folder containing the non-cleaned submissions." 
    vTcl:DefineAlias "$site_3_0.lab62" "Label4" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "btn_Clean" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Clean Submissions" 
    vTcl:DefineAlias "$site_3_0.but49" "nonCleanbtn" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Choose the empty folder that will contain the cleaned submissions." 
    vTcl:DefineAlias "$site_3_0.lab55" "Label7" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent47" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "vEntry" -width 394 
    vTcl:DefineAlias "$site_3_0.ent47" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_3_0.ent50" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "vEntry4" -width 394 
    vTcl:DefineAlias "$site_3_0.ent50" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.027 -y 0 -rely 0.362 -width 87 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.027 -y 0 -rely 0.769 -width 87 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.015 -y 0 -rely 0.582 -width 0 \
        -relwidth 0.98 -height 0 -relheight 0.18 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.763 -y 0 -rely 0.769 -width 117 \
        -relwidth 0 -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.015 -y 0 -rely 0.212 -width 0 \
        -relwidth 0.966 -height 0 -relheight 0.111 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 0 -relx 0.163 -y 0 -rely 0.779 -width 394 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 0 -relx 0.163 -y 0 -rely 0.382 -width 394 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    label "$top.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "- For best performance, place all your working files and folders on the same drive (e.g., C:/, D:/, or E:/). 
Accessing files across multiple drives may slow down the program due to increased I/O overhead." 
    vTcl:DefineAlias "$top.lab56" "Label6" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$top.lab51" \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000000 \
        -text "Cleaned Submissions" -background #d9d9d9 -height 364 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 711 
    vTcl:DefineAlias "$top.lab51" "frameBottom" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab51
    labelframe "$site_3_0.lab52" \
        -font "-family {Segoe UI} -size 10 -weight bold" -foreground #000000 \
        -text "Prepare Submissions" -background #d9d9d9 -height 256 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 686 
    vTcl:DefineAlias "$site_3_0.lab52" "frameBtmLeft" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab52
    button "$site_4_0.but55" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "btn_CopyOverride" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Copy and Override" 
    vTcl:DefineAlias "$site_4_0.but55" "btnCopyOverride" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Choose the folder containing the template Task_*.py and Testing_*.py files (e.g., TemplatePythonModel)" 
    vTcl:DefineAlias "$site_4_0.lab50" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_0.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "btn_GetCleanPath" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Select Folder" 
    vTcl:DefineAlias "$site_4_0.but48" "btnGetVenv" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_0.but54" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "btn_SetupVenv" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Setup Virtual Envs" 
    vTcl:DefineAlias "$site_4_0.but54" "btnSetVenv" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab63" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "IMPORTANT: Setup the venvs first before copying and overriding." 
    vTcl:DefineAlias "$site_4_0.lab63" "Label11" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_0.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "btn_GetTestPath" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Select Folder" 
    vTcl:DefineAlias "$site_4_0.but51" "btnGetCopyOverride" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Choose the folder containing the cleaned original submissions." 
    vTcl:DefineAlias "$site_4_0.lab54" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_0.ent49" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "vEntry3" -width 394 
    vTcl:DefineAlias "$site_4_0.ent49" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_0.ent48" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "vEntry2" -width 394 
    vTcl:DefineAlias "$site_4_0.ent48" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but55 \
        -in $site_4_0 -x 0 -relx 0.776 -y 0 -rely 0.83 -width 117 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 0 -relx 0.016 -y 0 -rely 0.678 -width 0 \
        -relwidth 0.977 -height 0 -relheight 0.096 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.016 -y 0 -rely 0.439 -width 87 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but54 \
        -in $site_4_0 -x 0 -relx 0.776 -y 0 -rely 0.448 -width 117 \
        -relwidth 0 -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab63 \
        -in $site_4_0 -x 0 -relx 0.19 -y 0 -rely 0.13 -width 0 \
        -relwidth 0.602 -height 0 -relheight 0.091 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but51 \
        -in $site_4_0 -x 0 -relx 0.016 -y 0 -rely 0.83 -width 87 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab54 \
        -in $site_4_0 -x 0 -relx 0.016 -y 0 -rely 0.304 -width 0 \
        -relwidth 0.975 -height 0 -relheight 0.096 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent49 \
        -in $site_4_0 -x 0 -relx 0.157 -y 0 -rely 0.848 -width 394 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent48 \
        -in $site_4_0 -x 0 -relx 0.157 -y 0 -rely 0.461 -width 394 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$site_3_0.lab53" \
        -font "-family {Segoe UI} -size 10 -weight bold" -foreground #000000 \
        -text "Run Tests" -background #d9d9d9 -height 91 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 683 
    vTcl:DefineAlias "$site_3_0.lab53" "frameBtmRight" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab53
    button "$site_4_0.but56" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Run Tests" 
    vTcl:DefineAlias "$site_4_0.but56" "btnRunTest" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but56 <Button-1> {
        lambda e: btnRunTest_lclick(e)
    }
    checkbutton "$site_4_0.che55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Task 2" -variable "che40" 
    vTcl:DefineAlias "$site_4_0.che55" "CheckTask2" vTcl:WidgetProc "Toplevel1" 1
    checkbutton "$site_4_0.che53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Task 4" -variable "che42" 
    vTcl:DefineAlias "$site_4_0.che53" "CheckTask4" vTcl:WidgetProc "Toplevel1" 1
    checkbutton "$site_4_0.che52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -command "btn_Checkboxes" -compound left \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -justify left -text "Task 1" \
        -variable "che39" 
    vTcl:DefineAlias "$site_4_0.che52" "CheckTask1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton "$site_4_0.che54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Task 3" -variable "che41" 
    vTcl:DefineAlias "$site_4_0.che54" "CheckTask3" vTcl:WidgetProc "Toplevel1" 1
    button "$site_4_0.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "btn_GetRunfolder" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Select Folder" 
    vTcl:DefineAlias "$site_4_0.but47" "btnGetRunfolder" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Choose the folder containing the prepared override scenarios" 
    vTcl:DefineAlias "$site_4_0.lab57" "Label3" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_0.ent51" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "vEntry5" -width 294 
    vTcl:DefineAlias "$site_4_0.ent51" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but56 \
        -in $site_4_0 -x 0 -relx 0.845 -y 0 -rely 0.44 -width 77 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.che55 \
        -in $site_4_0 -x 0 -relx 0.729 -y 0 -rely 0.22 -width 0 \
        -relwidth 0.109 -height 0 -relheight 0.264 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che53 \
        -in $site_4_0 -x 0 -relx 0.729 -y 0 -rely 0.659 -width 0 \
        -relwidth 0.09 -height 0 -relheight 0.264 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che52 \
        -in $site_4_0 -x 0 -relx 0.612 -y 0 -rely 0.22 -width 0 \
        -relwidth 0.09 -height 0 -relheight 0.264 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che54 \
        -in $site_4_0 -x 0 -relx 0.612 -y 0 -rely 0.659 -width 0 \
        -relwidth 0.09 -height 0 -relheight 0.264 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but47 \
        -in $site_4_0 -x 0 -relx 0.015 -y 0 -rely 0.571 -width 87 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.209 -width 0 \
        -relwidth 0.545 -height 0 -relheight 0.231 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent51 \
        -in $site_4_0 -x 0 -relx 0.16 -y 0 -rely 0.593 -width 294 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.064 -width 0 \
        -relwidth 0.965 -height 0 -relheight 0.631 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.712 -width 0 \
        -relwidth 0.965 -height 0 -relheight 0.25 -anchor nw \
        -bordermode ignore 
    label "$top.lab59" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "REMINDER: Dont forget to move Images, 
Testing files and CSV files!" 
    vTcl:DefineAlias "$top.lab59" "Label13" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but57 \
        -in $top -x 0 -relx 0.415 -y 0 -rely 0.944 -width 77 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.08 -y 0 -rely 0.944 -width 57 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.011 -width 0 -relwidth 0.189 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.128 -width 0 -relwidth 0.929 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.169 -width 0 -relwidth 0.949 \
        -height 0 -relheight 0.257 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.051 -width 0 -relwidth 0.93 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.428 -width 0 -relwidth 0.952 \
        -height 0 -relheight 0.501 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.935 -width 0 -relwidth 0.379 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top5 {base} {
    global vTcl
    if {$base == ""} {
        set base .top5
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m47 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 722x573+1346+515
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 5124 1678
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Help"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel2" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m47" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    button "$top.but53" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "btn_Close" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Close" 
    vTcl:DefineAlias "$top.but53" "closebtn" vTcl:WidgetProc "Toplevel2" 1
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 593 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 722 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Toplevel2" 1
    set site_3_0 $top.fra47
    label "$site_3_0.lab60" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10 -weight bold" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Non-Cleaned Submissions:" 
    vTcl:DefineAlias "$site_3_0.lab60" "Label5_1" vTcl:WidgetProc "Toplevel2" 1
    label "$site_3_0.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "First, create empty folder that is going to contain the submissios after being cleaned and then 
select that folder in the first entry. " 
    vTcl:DefineAlias "$site_3_0.lab47" "Label8" vTcl:WidgetProc "Toplevel2" 1
    label "$site_3_0.lab61" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Clean Submissions: Select the folder containing the zipped student submissions. The program will:

- Unzip each submission
- Rename folders based on student IDs
- Flatten unnecessary nested directories
- Remove irrelevant files

When completed, a message box will notify you and display the location of the cleaned submissions." 
    vTcl:DefineAlias "$site_3_0.lab61" "Label6_1" vTcl:WidgetProc "Toplevel2" 1
    label "$site_3_0.lab68" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10 -weight bold" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Cleaned Submissions:" 
    vTcl:DefineAlias "$site_3_0.lab68" "Label5_1_1" vTcl:WidgetProc "Toplevel2" 1
    ttk::separator "$site_3_0.tSe66"
    vTcl:DefineAlias "$site_3_0.tSe66" "TSeparator3" vTcl:WidgetProc "Toplevel2" 1
    label "$site_3_0.lab69" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "1. Setup Virtual Environments: After cleaning the submissions (unzipping, renaming, etc.), 
select the folder containing the cleaned submissions.

⚠️ This operation may take some time. Please monitor the shell (terminal/CMD) from which the GUI 
was launched for progress updates.

2. Copy Submissions and Override Files: Once virtual environments are ready, select the folder containing the tutor's 
version of the task and test files (e.g., Task_1.py, Task_2.py, Testing_1.py, Dummy.py, Helper.py, etc.)." 
    vTcl:DefineAlias "$site_3_0.lab69" "Label10" vTcl:WidgetProc "Toplevel2" 1
    label "$site_3_0.lab71" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "3. Run Test: Once everything is ready, choose the folder containing override scenarios (Original_Submissions, 
Task1_override, Task1_2_Override) and the desired tasks using the checkboxes and start the test process. 

When tests are completed, a message box will notify you, and a collated report will be generated automatically." 
    vTcl:DefineAlias "$site_3_0.lab71" "Label12" vTcl:WidgetProc "Toplevel2" 1
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely 0.02 -width 0 \
        -relwidth 0.247 -height 0 -relheight 0.036 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely 0.078 -width 0 \
        -relwidth 0.947 -height 0 -relheight 0.1 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely 0.184 -width 0 \
        -relwidth 0.962 -height 0 -relheight 0.273 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely 0.482 -width 0 \
        -relwidth 0.205 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe66 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -rely 0.469 -width 0 \
        -relwidth 0.856 -height 0 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely 0.527 -width 0 \
        -relwidth 0.967 -height 0 -relheight 0.285 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely 0.832 -width 0 \
        -relwidth 0.97 -height 0 -relheight 0.141 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but53 \
        -in $top -x 0 -relx 0.443 -y 0 -rely 0.925 -width 57 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.023 -width 0 -relwidth 0.973 \
        -height 0 -relheight 0.894 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top4 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top5 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}

